### ISSUE TITLE
running a shell command with sudo

### ISSUE THREAD

**Issue by Lompik** [wasamasa/firestarter#11]
Currently, running a Shell command containing sudo in Firestarter will not succeed. For example 

```
# Local Variables:
# firestarter: "sudo salt-cp -L 'serv1' /home/nginx/nginx.conf /etc/nginx/nginx.conf"
# End:
```

I've stumble upon this [SO](http://stackoverflow.com/questions/2472273/how-do-i-run-a-sudo-command-in-emacs) question and possible solutions are: 
- ask pw with an emacs interactive function and pipe it to `sudo -S`. However that won't cache the pw. Also if the command fails the pw ends up in the `*messages*` buffer.
- add salt-cp to the sudoers with no password. 

Do you see any other alternatives ?

**Comment by wasamasa** [comment]
Whitelisting a command by adding it to `/etc/sudoers` sounds like a bad idea to me, simply because how easy it is to exploit by a malicious third-party.

I'm not sure why a password can end up being printed to `*messages*`.  Here's an example that doesn't appear to do so:

``` elisp
(defun my-run-with-sudo (&rest args)
  (let ((pw (password-read "Enter password: "))
        (sudo-process (apply 'start-process "Sudo" "*sudo*" "sudo" "-S" args)))
    (process-send-string sudo-process pw)))
```

Finally, the caching thing is a `sudo` feature that relies on a number of things, including the pty to be the same.  If you for example use it in one pty, kill it and use it again in a new one, caching won't apply.  This is also why `gksudo` (and probably `kdesu` as well) can't make use of it.  Disabling it with a `Defaults !tty_tickets` line will allow you to use `gksudo` in your command and not being asked again for the caching period after an initial question for your password.  You could alternatively be using `sudo` with it, but I wouldn't recommend that as it was written with terminals in mind and detecting whether you need to supply a password is sort of silly if `gksudo` does it already for you.

**Comment by Lompik** [comment]
Thanks ! It turns out it needs a newline character.

```
(process-send-string sudo-process (concat pw "\n")))
```

It would probably be best to send the sudo in a tty environment which lifetime would cache the password. Although I can't find a solution for that now.

Another solution would be using the password-cache.el the same way as Tramp does.

**Comment by wasamasa** [comment]
Oh indeed, I forgot that in my example.  You could certainly configure the time limit for sudo globally, but that feels even unsafer than the alternative of caching beyond ptys.

**Comment by Lompik** [comment]
So it turns out that's exactly what `Tramp` (I use this for editing local files as root) does. It creates a /bin/sh shell and keeps it alive. With an extended sudo setting (namely `Defaults:username timestamp_timeout=360`), password is remembered in the shell.

So I ended using this :

```
# Local Variables:
# firestarter: (tramp-send-command (vector tramp-current-method tramp-current-user tramp-current-host nil nil) "sudo salt-cp -L 'serv1'' /home/nginx/nginx.conf /etc/nginx/nginx.conf" nil 1)
# End:
```

with the vector evaluating to : `"sudo" "root" "yourhostname"`

Also, it seems to me that `password-cache.el` (used by `Tramp`) store passwords in memory in an unencrypted form for 16 seconds (default setting). So I'll probably never set `password-cache-expiry` to nil.

**Comment by wasamasa** [comment]
Nice, thanks for figuring that out.
